ChatApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve 
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
   
]

if settings.DEBUG == False:
    urlpatterns+=[ url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),]

chat/urls.py
from django.contrib.auth.views import logout
from django.urls import path
from . import views





urlpatterns = [
    path('', views.home, name='home'),
    
    path('ask', views.response, name='response'),

    path('administration', views.index, name='index'),
    path('administration/login', views.AdLogin, name='adminlogin'),
  
    path('chat_viewMY/', views.chat_viewMY, name='chat_viewMY'),

    path('trianbot/', views.trianBot, name='trianBot'),

 
    path('chat1/<int:reciver>/', views.message_view1, name='chat1'),


    
    path('api/messages1/<int:sender>/<int:receiver>', views.message_list1, name='message-detail1'),
    path('api/messages1/', views.message_list1, name='message-list1'),
    
    path('logout/', logout, {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)





class chatusers(models.Model):
    ip=models.CharField(max_length=255 , unique=True )
    timestamp = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return self.ip
    
    class Meta:
        ordering = ('timestamp',)
    


class MessageChat(models.Model):
    sender = models.IntegerField()
    receiver = models.IntegerField()
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['username','password1','password2']
        widgets = {
            'username': TextInput(attrs={'class':'form-control'}),
        }

chat/views.py
from genericpath import samestat
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message , chatusers, MessageChat
from chat.forms import SignUpForm
from chat.serializers import CreateSerializer, MessageSerializer, UserSerializer
from ChatApp.settings import ChatMode
from .functions.function import handle_uploaded_file

from .chat import responce, train

f = open('C:/Users/mishr/Desktop/project/Dataset.csv', 'r', encoding='utf-8')
print(f)

traindata=train(f)

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip



def home(request):
    context={}
    try:
        getchatuser=chatusers.objects.filter(ip=str(get_client_ip(request)))
        if  not getchatuser.exists():
            print('jdsflkdslkfjsdjfldskfjlsd')
            getchatuser=chatusers.objects.create(ip=str(get_client_ip(request)))
        context={'ip':get_client_ip(request),'sender':getchatuser[0].id,"ChatMode":ChatMode}
    except:
        return redirect('home')
    # print(type(context['ip']))
    return render(request, 'chat/userchat.html', context)


@csrf_exempt
def response(request):
    global traindata
    if request.method=="POST":
        data = JSONParser().parse(request)
        print('this is data', end='->')
        # print(request.POST)
        print(data['message'])
        k=chatusers.objects.filter(ip=data['sender'])[0].id
        data['sender']=k
        # print(data)
        serializer = CreateSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            print("this is chatbot status-->" , end="")
            print(ChatMode)
            if ChatMode:
                print("flkdjfls")
                r=responce(traindata,data['message'])
                print(r)
                print("this is msg form bot:"+str(r))
                serializer1 = CreateSerializer(data={'message':str(r),"receiver":k,"sender":22})
                if serializer1.is_valid():
                    print("this is gotta be true")
                    serializer1.save()
            else:
                pass
            return JsonResponse(serializer.data, status=201)
       
        return JsonResponse({'answer':"hwllo"} , safe=False)


def createHistory(request):
    data = request.POST["messageText"]
    print("sdjfj")
    serializer = MessageSerializer(data=data)
    if serializer.is_valid():
        serializer.save()
        return JsonResponse(serializer.data, status=201)
    return JsonResponse(serializer.errors, status=400)



def chat_viewMY(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/chat1.html',
                      {'users': chatusers.objects.all()})



def AdLogin(request):
    context={}
    if request.user.is_authenticated:

        return render(request, 'chat/adminDashboard.html', context)

    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("index")
        else:
            context['msg']="wrong credintial"
        
    return render(request, 'chat/login.html', context)


def index(request):
    context={}
    if not request.user.is_authenticated:
        return redirect("adminlogin")

    global ChatMode

    if request.method=="POST":
        bmode=request.POST
        print(bmode)
        for i in bmode:
            if i=='manual':
                ChatMode=False
            if i=='bot':
                ChatMode=True
    context={"mode":ChatMode}
    print(context)
    print(ChatMode)

        
    return render(request, 'chat/adminDashboard.html', context)





@csrf_exempt
def message_list1(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    # print("your got hear")
    if request.method == 'GET':
        messages = MessageChat.objects.filter(sender=sender, receiver=receiver, is_read=False)
        serializer = CreateSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        print(data)
        # serializer = MessageSerializer(data=data)
        serializer = CreateSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
        else: print("data is not valid")
            # return JsonResponse(serializer.data, status=201)
        # return JsonResponse(serializer.errors, status=400)
        print("this is post requests")
        return JsonResponse({'answer':"hwllo"} , safe=False)
        


def register_view(request):
    """
    Render registration template
    """
    if request.method == 'POST':
        print("working1")
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('chats')
    else:
        print("working2")
        form = SignUpForm()
    template = 'chat/register.html'
    context = {'form':form}
    return render(request, template, context)




def message_view1(request, reciver):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, "chat/messages1.html",
                      {'users': chatusers.objects.all(),
                       'receiver': chatusers.objects.get(id=reciver),
                       'messages': MessageChat.objects.filter(sender=22, receiver=reciver) |
                                   MessageChat.objects.filter(sender=reciver, receiver=22)})


def trianBot(request):
    global traindata
    

    context={}
    if request.method=="POST":
        print("fsjfjsl")
        print(request.FILES)
        k=request.FILES['docfile']
        print(k)
        handle_uploaded_file(k)
        try:
            f = open('upload/'+ k.name, 'r', encoding='utf-8')
            traindata=train(f)
        except:
            context['err']="Something Went Wrong/maybe file is not csv or formate is wrong"
        print(traindata)
        context['file']="File Successfully Uploaded"
        print("request is post")
        print(context)
    return render(request, 'chat/trainbot.html',context)


def testPrint():
    print(testVAr)

def test(a):
    global testVAr
    testVAr=a
    print("this test is runnig")

templates/chat/adminDashboard.html
{% extends 'chat/index.html' %}

{% block title %}Admin{% endblock %}

{% block stylesheets %}
<style>
    
.formbtn{
        display: flex;
  justify-content: center;
  align-items: center;
    }
.centerDiv{
        position: absolute;
  	left: 50%;
  	top: 50%;
  	transform: translate(-50%, -50%);
    }
.nav{
    padding: 0px 15px !important
}
</style>

{% endblock stylesheets %}



{% block body %}

    <nav>
    
        <div class="navbar-fixed nav container">
        <a href="{% url 'index' %}" class="brand-logo ">Intelligent Chatbot</a>
        
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a  href="{% url 'trianBot' %}">TrainBot</a></li>
            <li><a href="{% url 'chat_viewMY' %}">Chat</a></li>
            <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
        </ul>
        </div>

    </nav>

    
    <div class="centerDiv">
        <h1 class="center">
            {% if mode == False %}
                Curently System is in Manual Mode
            {% else %}
            Curently System is in bot Mode
            {% endif %}
        </h1>
        <div class="center-block formbtn">
            <form method='post'>
                {% csrf_token %}
                <button class="btn btn-large waves-effect waves-purple darken-1 " name='bot' value="bot">Bot Mode</button>
                <button class="btn btn-large" name='manual' value="manual"> Manual Mode</button>
            </form>
        </div>
    </div>
    

{% endblock body %}


{% block javascripts %}
   
{% endblock javascripts %}

templates/chat/chat1.html
{% extends 'chat/index.html' %}
{% block body %}
<nav class="lighten-3" >
    <div class="nav-wrapper container">
      <a href="{% url 'index' %}" class="brand-logo center">ChatBot</a>
      <ul id="nav-mobile" class="left " >
          <li><a href="{% url 'chat_viewMY' %}" >Chat</a></li>
          <li><a href="{% url 'trianBot' %}" >TrainBot</a></li>
      </ul>
      
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href=""> Hello {{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>

</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
            <div class="card">
                <div class="collection">
                    {% for user in users %}
                    <a href="{% url 'chat1' user.id %}" id="user{{ user.id }}" class="collection-item row">
                        {% comment %} <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg" class="col s4"> {% endcomment %}
                        <img src="https://img.icons8.com/color/96/000000/user.png" class="col s4"/>
                        
                        <div class="col s8">
                            {% comment %} <i class="material-icons">notifications</i>
                            <span class="material-icons">
                                notifications_active
                                </span> {% endcomment %}
                        <span class="title" style="font-weight: bolder"> user {{ user.id }} <br> {{ user.ip }}</span>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>

            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating lighten-2 waves-effect waves-light" style="background-color: gray"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            
            </div>
        </div>
    </div>
    </div>
    {% load staticfiles %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>

        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send1('{{ receiver.id }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

templates/chat/index.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
        <title>
        {% block title %}{% endblock %}
        </title>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
        
        {% block stylesheets %}

        {% endblock stylesheets %}
    </head>
  

    <body>
    {% block body %}
       
        {% endblock %}
    </body>
    {% block javascripts %}
   
    {% endblock javascripts %}
  </html>

templates/chat/login.html
{% extends "base/baseAdmin.html" %}
{% block title %}Admin Login{% endblock %}

{% block stylesheets %}

<style>
    /* Coded with love by Mutiullah Samim */
    body,
    html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #60a3bc !important;
    }
    .user_card {
        height: 400px;
        width: 350px;
        margin-top: auto;
        margin-bottom: auto;
        background: #f39c12;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

    }
    .brand_logo_container {
        position: absolute;
        height: 170px;
        width: 170px;
        top: -75px;
        border-radius: 50%;
        background: #60a3bc;
        padding: 10px;
        text-align: center;
    }
    .brand_logo {
        height: 150px;
        width: 150px;
        border-radius: 50%;
        border: 2px solid white;
    }
    .form_container {
        margin-top: 100px;
    }
    .login_btn {
        width: 100%;
        background: #c0392b !important;
        color: white !important;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }
    .input-group-text {
        background: #c0392b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .custom-checkbox .custom-control-input:checked~.custom-control-label::before {
        background-color: #c0392b !important;
    }
</style>
{% endblock stylesheets %}


{% block content %}
   {% comment %} <h1>this is admin login page</h1> {% endcomment %}
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <div class="brand_logo_container">
                        {% comment %} <img src="https://cdn.freebiesupply.com/logos/large/2x/pinterest-circle-logo-png-transparent.png" class="brand_logo" alt="Logo"> {% endcomment %}
                        <img src="https://img.icons8.com/color/96/000000/admin-settings-male.png"  class="brand_logo bg-danger" alt="Logo"/>
                    </div>
                </div>

                
                
                <div class="d-flex justify-content-center form_container">
                    
                    <form  method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" class="form-control input_user" value="" placeholder="username">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" class="form-control input_pass" value="" placeholder="password">
                        </div>

                        {% comment %} <div class="form-group">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="customControlInline">
                                <label class="custom-control-label" for="customControlInline">Remember me</label>
                            </div>
                        </div> {% endcomment %}

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <button type="submit" name="button" class="btn login_btn">Login</button>
                        </div>
                    </form>
                </div>
        
                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        <ul class="list-group">
                        {% if msg %}
                        <li class="list-group-item list-group-item-danger">{{ msg }}</li>
                        {% endif %}

                        </ul
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block javascripts %}
   
{% endblock javascripts %}

templates/chat/messages1.html
{% extends 'chat/chat1.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}

    {% if message.sender == request.user.id %}

<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>

    {% else %}

<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">User-{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}

<script>

$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive1,1000)
})
</script>
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Username</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Repeat Password</label>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Register</button>
                </div>
                </div>
            </div>
    </form>
{% endblock %}

templates/chat/trainbot.html
{% extends 'chat/index.html' %}

{% block title %}Admin{% endblock %}

{% block stylesheets %}
<style>
    
.formbtn{
        
    width:25rem;
    height:3.4rem;
    margin:1rem; !important;
    background : #3c4f76;
   
    }

.centerDiv{
        position: absolute;
  	left: 50%;
  	top: 50%;
  	transform: translate(-50%, -50%);
    }
.msgAfS{
    margin-top:5rem;
    text-align: center;
    color:#0bda51;
}
.msgerr{
    margin-top:5rem;
    text-align: center;
    color:red;
}

</style>

{% endblock stylesheets %}



{% block body %}

<nav class="lighten-3" >
    <div class="nav-wrapper container">
      <a href="{% url 'index' %}" class="brand-logo center">ChatBot</a>
      <ul id="nav-mobile" class="left " >
          <li><a href="{% url 'trianBot' %}" >TrainBot</a></li>
          <li><a href="{% url 'chat_viewMY' %}" >Chat</a></li>
      </ul>
      
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href=""> Hello {{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>

</nav>

    {% if  err   %}
    <h6 class="msgerr">{{ err }}</h6>
    {% else %}
    <h4 class="msgAfS">{{ file }}</h4>

    {% endif %}


    <div class="centerDiv">
        <form method="post" enctype="multipart/form-data">
     {% csrf_token %}

            <div class="file-field input-field">
              
              <div class="btn">
                <span>File</span>
                <input name="docfile" type="file" >
              </div>
              
              <div class="file-path-wrapper">
                <input   class="file-path validate" type="text" placeholder="Upload one or more files">
              </div>
            </div>
            <button class="btn formbtn">submit</button>
          </form>
    </div>
    

{% endblock body %}


{% block javascripts %}
   
{% endblock javascripts %}